### PR TITLE
Get accurate IP for redirectors

### PR DESCRIPTION
**Pull request by vysecurity**
## What does it do?

Takes the external IP address from the HTTP packet if it exists to display the IP address of the external client instead of the intermediate proxy.

## How did you do it?

Added retrieval of the information from HTTP header.

### CODE REVIEW

**Comment by chvancooten** [comment]
Since no verification depends on external IPs this fix should be fine. Theoretically, there could be cases where `X-Forwarded-For` contains multiple IP addresses I think, so potentially it needs some hardening there to prevent bugs. Looks good otherwise, will include it for 1.1 👍

**Comment by chvancooten** [comment]
Added a commit in the Dev branch that implements this a bit more robustly. Feel free to play around with it and let me know if it works well for your intended use case as well!

**Comment by vysecurity** [comment]
It's alright if it contains multiple IP addresses ;-) sometimes you need the path.

**Comment by chvancooten** [comment]
Which path do you mean? The parsed header should always point to the first IP address in the chain right?

**Pull request closed without merging**
