### PR TITLE
fix mingw flags for default Nim installation on ArchLinux

### PR DESCRIPTION
**Pull request by tothi**
This config tweak was needed on Arch, idk if it is needed elsewhere, but probably won't harm.

### CODE REVIEW

**Comment by chvancooten** [comment]
Thanks for the PR! Itś not immediately apparent to me what impact this may have on other builds, it looks fairly benign. if the CI/CD builds pass I'll do some manual checks and let you know!

**Comment by tothi** [comment]
Ok, thanks. Now I am a little bit uncertain whether this should be added to the build or not, because the issue is a Nim+Mingw issue, not  related strictly to Nimplant (and affects only Arch as I know currently). If you have also doubts, probably a note about this in the README is a better solution (with a link to e.g. this: https://gist.github.com/tothi/1f452e0466070db5921135ab312749fc )

**Comment by chvancooten** [comment]
Thanks! I agree with that idea, though the builds seem to be passing I can't tell entirely what these configurations may do on other systems and it's not immediately related to Nimplant anyways. Closing this PR but I added a note to the readme, with the gist you shared and a word of credit :)
Thanks again!

**Comment by tothi** [comment]
awesome, thanks! :)

**Pull request closed without merging**
